### ISSUE TITLE
rdf: のprefix uriが間違っている

### ISSUE THREAD

**Issue by fumi** [InfoLoungeLLC/IMIDataConverter#2]
プロパティとして rdf:type を入力したときにTurtleで出力をすると以下のようになります。

@prefix ns0: http://www.w3.org/1999/02/22-rdf-syntax-ns#/ .

最後の'/'が必要ないので削除してください。
また、可能ならprefix nameをns0ではなくrdfにして欲しいです。

**Comment by soutaito** [comment]
17bf3f3c06d63383e4c2429f16faef02046abaf6 にて対応しました。
