### ISSUE TITLE
header.ttlの出力バグ

### ISSUE THREAD

**Issue by fumi** [InfoLoungeLLC/IMIDataConverter#6]
convertedData.turtleとなってしまっているのはconvertedData.ttlだとおもいます。

dcat:distribution &lt;convertedData.turtle> .
=>
dcat:distribution &lt;convertedData.ttl> .

&lt;convertedData.turtle> a adms:AssetDistribution ;
=>
&lt;convertedData.ttl> a adms:AssetDistribution ;

**Comment by soutaito** [comment]
281a2002bbafcbae61fa496d6b79736fb4f3dcc0 にて、DMDのヘッダーファイル仕様への準拠とともに修正されました。
